export { default as Nav } from './nav/nav'
export { default as Header } from './header/header'
export { default as Home } from './home/home'
export { default as Resume } from './resume/resume'
export { default as Contact } from './contact/contact'
